apiVersion: v1
kind: Namespace
metadata:
  name: nm-postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: nm-postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: dbtest
  POSTGRES_USER: dbuser
  POSTGRES_HOST: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nm-postgres
  labels:
    app: postgres
data:
  # Welcome1!
  POSTGRES_PASSWORD: V2VsY29tZTEh
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-persistent-volume
  namespace: nm-postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-persistent-volume-claim
  namespace: nm-postgres
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nm-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nm-postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

# kubectl exec --namespace=nm-postgres -it $(kubectl get pods --namespace=nm-postgres | awk 'NR==2 {print $1}') -- /bin/bash
# psql -h localhost -U dbuser -W dbtest